<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1VN6NSF" failures="1" tests="4" name="com.practiceTestNG.PracticeAssert" time="10.338" errors="0" timestamp="2023-11-23T15:43:27 IST" skipped="2">
  <testcase classname="com.practiceTestNG.PracticeAssert" name="assertStringTest" time="1.058">
    <skipped/>
  </testcase> <!-- assertStringTest -->
  <system-out/>
  <testcase classname="com.practiceTestNG.PracticeAssert" name="assertStringTest" time="3.186">
    <skipped/>
  </testcase> <!-- assertStringTest -->
  <system-out/>
  <testcase classname="com.practiceTestNG.PracticeAssert" name="assertStringTest1" time="4.757"/>
  <system-out/>
  <testcase classname="com.practiceTestNG.PracticeAssert" name="assertStringTest" time="1.337">
    <failure message="Match Found expected [Staff] but found [StaffLogin]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Match Found expected [Staff] but found [StaffLogin]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.banking.bixi.POM.BixiStaffLoginPage.stafftextverify(BixiStaffLoginPage.java:55)
at com.practiceTestNG.PracticeAssert.assertStringTest(PracticeAssert.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- assertStringTest -->
  <system-out/>
</testsuite> <!-- com.practiceTestNG.PracticeAssert -->
